import type { Metadata } from "next";
import "@/styles/globals.css";
import BackgroundImage from "@/ui/atoms/backgroundImage";
import SeasonalEffect from "@/ui/terrace/seasonal-animation";
import { CalendarProvider } from "@/contexts/calendar-context";

export const metadata: Metadata = {
  title: "縁側",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <CalendarProvider>
        <div data-layout="background" className="relative">
          <BackgroundImage imageUrl="/images/sample-engawa.jpeg" />
          <SeasonalEffect season="spring" />
        </div>
        <main className="relative z-0 min-h-screen w-full flex-grow">
          {children}
        </main>
      </CalendarProvider>
    </>
  );
}
