import type { Metadata } from "next";
import "@/styles/globals.css";
import BackgroundImage from "@/ui/atoms/backgroundImage";
import DynamicButtonsArea from "@/ui/templates/dinamic-buttons-area";

export const metadata: Metadata = {
  title: "home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <BackgroundImage imageUrl="/images/sample-engawa.png" />
      <main className="relative z-0 w-full">{children}</main>
      {/* <DynamicButtonsArea /> */}
    </>
  );
}
