import type { Metadata } from "next";
import "@/styles/globals.css";
import { appTitle } from "@/lib/utils/fonts";
import { Sprout } from "lucide-react";
import HelpNavigation from "@/ui/organisms/help-navigation";
import LinkButtonTerrace from "@/ui/atoms/link-button-terrace";

export const metadata: Metadata = {
  title: "home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <main className="relative z-0 min-h-screen w-screen flex-grow bg-amber-50">
        <div
          data-layout="official-title"
          className="bg-[var(--app-home-base-color)]/75 py-2 h-full"
        >
          <h1
            className={`m-auto flex items-center px-4 text-[var(--app-primary-color)] md:max-w-[80vw] ${appTitle.className}`}
          >
            <Sprout />
            えんがわ＋Diary
          </h1>
        </div>
        {children}
        <LinkButtonTerrace />
      </main>
      <HelpNavigation />
    </>
  );
}
