import type { Metadata } from "next";
import { system } from "../lib/fonts";
import "@/styles/globals.css";

export async function generateMetadata(): Promise<Metadata> {
  return {
    title: {
      default: "みどりぽ -私の脱！家庭菜園日誌-",
      template: "%s | みどりぽ -私の脱！家庭菜園日誌-",
    },
    description: "Generated by create next app",
  };
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${system.className} font container mr-auto ml-auto text-base text-gray-800`}
      >
        {children}
      </body>
    </html>
  );
}
