import type { Metadata } from "next";
import "@/styles/globals.css";
import Footer from "@/ui/templates/footer";
import { Providers } from "./providers";

export async function generateMetadata(): Promise<Metadata> {
  return {
    title: {
      default: "えんがわ＋Diary　家庭菜園から始める始める農ライフ",
      template: "%s | えんがわ＋Diary　家庭菜園から始める始める農ライフ",
    },
    description: "Generated by create next app",
  };
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="font relative mr-auto ml-auto w-full text-base">
        <Providers>{children}</Providers>
        <Footer />
      </body>
    </html>
  );
}
