import type { Metadata } from "next";
import "@/styles/globals.css";
import Footer from "@/ui/atoms/footer";
import { Providers } from "./providers";

export async function generateMetadata(): Promise<Metadata> {
  return {
    title: {
      default: "みどりぽ -私の脱！家庭菜園日誌-",
      template: "%s | みどりぽ -私の脱！家庭菜園日誌-",
    },
    description: "Generated by create next app",
  };
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="font mr-auto ml-auto w-full text-base">
        <Providers>{children}</Providers>
        <Footer />
      </body>
    </html>
  );
}
