import type { Metadata } from "next";
import "@/styles/globals.css";
import { system } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main
      className={`${system.className} container flex min-h-[100vh] w-full flex-col items-center justify-start bg-green-200 saturate-50 filter`}
    >
      {children}
    </main>
  );
}
