import type { Metadata } from "next";
import "@/styles/globals.css";
import DynamicButton from "@/ui/atoms/dynamic-button";
import BackgroundImage from "@/ui/atoms/backgroundImage";

export const metadata: Metadata = {
  title: "home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <BackgroundImage imageUrl="/images/sample-home-bg.jpeg" />
      <main className="relative w-full">{children}</main>
      <DynamicButton />
    </>
  );
}
