import type { Metadata } from "next";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="flex w-full flex-col items-center justify-start bg-green-200 saturate-50 filter">
      {children}
    </main>
  );
}
